basic.forever(function () {
    basic.pause(1000)
    basic.showArrow(ArrowNames.North)
    basic.showNumber(2)
    basic.pause(1000)
    basic.showArrow(ArrowNames.West)
    basic.showNumber(4)
    basic.pause(1000)
    basic.showArrow(ArrowNames.North)
    basic.showNumber(4)
    basic.pause(1000)
    basic.showArrow(ArrowNames.West)
    basic.showNumber(3)
    basic.pause(1000)
    basic.showArrow(ArrowNames.North)
    basic.showNumber(12)
    basic.pause(1000)
    basic.showArrow(ArrowNames.West)
    basic.showNumber(20)
    basic.pause(1000)
    basic.showArrow(ArrowNames.South)
    basic.showNumber(5)
    basic.pause(1000)
    basic.showArrow(ArrowNames.West)
    basic.showNumber(2)
    basic.showString("Llegue ")
    basic.pause(1000)
})
